import { defekt } from "../deps/defect.ts";

export class ShimPotentiallyInvalid extends defekt({
  code: "ShimPotentiallyInvalid",
  defaultMessage: `
  The command shim may not have been generated by "deno install" 
  or by a newer version which changed the deno shim format.`,
}) {}
